name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    env:
      TABLENAME: ${{ secrets.TABLENAME }}
      ACCESS_ID: ${{ secrets.ACCESS_ID }}
      BUCKET: ${{ secrets.BUCKET }}
      REGION: ${{ secrets.REGION }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
      - name: Install dependencies
        run: pnpm i
      - name: Run your tests
        run: npx playwright test
        env:
          HOME: /root
